language: generic
sudo: required
dist: trusty
env:
  global:
  - secure: gqFiFFryn1ysYGmQyFonPpE9jTK3sSPAga0WjY33uoE/RaaYWAjjdLT4QxHFNlPuviPmEB5M859LXBkhutuCyH1TkWkrHfj0ElIsH8vpXNDRjBDAoz8oAfyHm/4Z4if/7/LuE4hvVFEXtLj3rWc3UG6OPBPXUBM14OByCHrkKHvoSwfbvnuQsZeCl0P0NXjo+2ilLMkIR/Rb32bm7TWjhm2gvbP3eFnk/3GDicHXDpnrJ2apSo3/6guSvudAAPLsYvBQgT8wYslA3obULOlpvCEdrOqPIsO0GQoBOVdc/V7kF80KI4L2YNHsMGGDTWlEBbQSHTMF9qjdxTjA9spw1rGwgdcH36EJcOBNZnAo4SglDx9Llw8+knsa31ucHOQUSx1gDZAc6Kyxs09N8djaQiaZmEsC1g4bFxWxAU2PLyHZLj1lmV4g3yZyHz6f+HGQgqw385W9CAHVJHx3660VwWxfPVt83pXFCVNe/lVYnNNPCCCNfwnnjmuEB3Qeksu1t5adz8s903D9r3/TIbfe2DiUh3Kit46+SYnS01iLsHCBa+eXM6k3yEvHGI8l3TzgJ+6egrtjJpW8z9cCIXocWFz53hYtB+u+OBffXNs9Ow4kDHlgwz0WzZk3Z1Q+5tDSI39RgW4uPbNfH6ZQARyus+pKPVbAmckiSVlizvc/qcA=
  - secure: lv45qoMCveqF2DIwfjNvW9GXhLiLpzIXodUjd6+HFzklbm8T9CNvkqG1xfe7yksh9gnDW89EWLqnK8u+/+Bt7631iJnyMN+JCjv6h7LYsk6AdvFM4+972EvoSw8/f0cB3sj8UscTvKAeH7L93keScOtWh54tgaeDKl2O/nlUuV8PH9qYrIcD+YulQwCZJupviFGY3O8OAJ+bxfO/l1xd7dPUoK/rCqGzIeKvtjJKIAJSdLX5V1RdHSw+IglTGQdTHMc7HCXRFWUFYrrRaArk99ZlFLqmIw6t7G5E3H3q4ljF0R4NnL3bKopHnrAgqkaEin4TZFKx5OPYcjptzTd/thg5CKJHScPYOnKk3yKHU1OYt2P+/SUCjHPyenLs7u66bEWAj+bAW99zfVpV3dQvImpg2tf7CrMqgTVzH9x4s2mYK7GtUxDtFnPdXFJhhap/cxajz2XN/GntFhRnNrbmfbMiOUjs4l0JRFuqUmfiIsh0Ebt6pke6V6+Wp4twTwyAG68EDyn71ncMeEWzh+MV2e8GrA4EcRjVKcKojfsJ1qW9BNrnijI6MPWmW+q1p6P2B2zLf96EXeR/QyiADiJqE1mqxd9qJz27VYdGj4x+4NXojm12Xnr4rCbjuoMMp6cI2VlTNtBUIwmj9u5rmD0wcYkuPQbdc1GkGt641+BZtZY=
  - secure: DbLNHOR/AsDEbMSk9jMG2KtuCwSCE9YKCsVaL13ff584gx9Z5nOKyaTMaokUFwVz0jibkPLVO+zsTjW1DnDEcFOQ45rmlJV9iNguEEXRBhtTGp7axZub7ufGFv6dp/ktnbt3ltJqvbArCx3nCJ3aKQY4sNfsHOfrlUNtG2k5I1EQOIAH95jd1B1ApLl1eBe9W912Hhf+EohoNvgyjc54B7QXCDIUOVKcA6zN1jT7RrBGPFPkvwEW5gELqpo+6kmZRFutsEKvdRrZTetInuSE9In4qDl7stE5OmS7Ltiktmdryn1G8JMokXzlS66wMlGWCyHtBYNskSK9pmOwRZvcUwr1eUua5J33dc/uBEORyMvWVlWVUht2C5PYtqPd17LKBwHpY1JoeABMBxVG6l8H327BhHHYaNLTRx6YxHhJHj1DaoFAflaapqlQu0DQtTkStPkEQV69/nzifPHLbD9dWfPlklhPhTjqWhngXoTGtyT2StdK/LGvWgPsVMZmYmoiT+YiJlExo+FJYyXiZg+asPjZ1gmMTuQLyY5v35hHeNNpO+OkwmxaAVE3BvkUiPrp4Foq8zevs6NbDKrv70rRL4zVRp4+N0O1XQS9+wzxi7X3gX480SUBy5f1ZmhODVl+zk6EXQVgW99Nw3QMFFK2xtHMq5KgRGqXBn3RhXjtIvI=
services:
- docker
before_script:
- printenv | awk -F= '{if ($1 ~ /^(TRAVIS|GITHUB)/) print $1"="$2}' > .env
- docker-compose build --build-arg GITHUB_CREDENTIALS_TOKEN=$GITHUB_CREDENTIALS_TOKEN web
script:
- docker-compose run web typesafety --review
- docker-compose run web composer test
matrix:
  fast_finish: true
notifications:
  email: false
